### ISSUE TITLE
dpv:isIndicatedAtTime as ObjectProperty

### ISSUE THREAD

**Issue by beyzayaman** [coolharsh55/dpv-x#1]
I guess dpv:isIndicatedAtTime should be listed as a Datatype Property instead of ObjectProperty in dpv.owl document.

**Comment by coolharsh55** [comment]
Hi. The dpv repo is actually at - https://github.com/w3c/dpv/ ; could you please move your issue there? This repo is the experimental stuff I do with dpv. I will copy my answer over as well.

To answer your question: What I've done so far is to make it an ObjectProperty if the domain or range is defined, otherwise an AnnotationProperty. In OWL, AFAIK there's no good way to indicate a general property. For e.g. time can be a Time ontology object or a timestamp expressed as a string or using XSD. If you have a suggestion to improve this, please share it.
